export const LINES = `
  : FloppaBoot(TM) v3.12.1
  : Floppa is a registered trademark of Floppa Manufacturing, LTD
  : All Rights Reserved
  : 
sleep 300
  : Starting Power-on Self Test...
  : 
sleep 200
  : CPU: Nokia(R) Mote(TM) Transverse CPU @ 9.21GHz
  :   Speed: 9.20GHz
  :   Count: 256
  : 
sleep 50
  : RAM: GigaDIMM(TM) Antisynchronous 1.23THz (0.8ps)
  :   Size: (-32 + 3i)KiB
  : 
sleep 50
  : Caches (sum of all):
  :   L1d:      9MiB (256 Instances)
  :   L1i:      12MiB (256 Instances)
  :   L2:       1GiB (64 Instances)
  :   L3:       2GiB (8 Instances)
  :   L4:       4GiB (1 Instance)
  :
sleep 50
  : PCI Devices:
  : Bus  PID  Class  Device
  :   0    1   9007  Nokia Mote CPU Host Bridge
  :   0    4   4ac1  USB 5.0 Host Controller
  :   0  4.1   4ac1  USB 5.0 Host Controller
  :   0  4.2   4ac1  USB 5.0 Host Controller
  :   0  4.3   4ac1  USB 5.0 Host Controller
  :   2    6   b606  IDE Controller
  :   1  6.1   45a8  SMBus Controller
  :   1    7   bf0d  Display Controller
  :   0    8   f2e7  Neural Accelerator
  :   2   12   6a2f  PCI Bridge
  : 
sleep 400
  : Booting from Floppy Drive A...
  : 
sleep 400
  : /dev/sda5: clean, 373574/907536 files, 3200659/367264 blocks
OK: Reached target sysinit.target - System Initialization.
OK: Started plymouth-start.service - Show Plymouth Boot Screen.
OK: Started systemd-ask-password-plymouth.path - Forward Password Requests to Plymouth Directory Watch.
OK: Reached target paths.target - Path Units.
OK: Reached target basic.target - Basic System.
OK: Reached target initrd-root-device.target - Initrd Root Device.
OK: Finished dracut-initqueue.service - dracut initqueue hook.
OK: Reached target remote-fs-pre.target - Preparation for Remote File Systems.
OK: Reached target remote-fs.target - Remote File Systems.
__: Starting systemd-fsck-root.service - File System Check on /dev/disk/by-uuid/b80d5d3f-371a-4008-b19e-3d0c5a8b05dc...
OK: Finished systemd-fsck-root.service - File System Check on /dev/disk/by-uuid/b80d5d3f-371a-4008-b19e-3d0c5a8b05dc.
__: Mounting sysroot.mount - /sysroot...
OK: Mounted sysroot.mount - /sysroot.
OK: Reached target initrd-root-fs.target - Initrd Root File System.
__: Starting initrd-parse-etc.service - Reload Configuration from the Real Root...
OK: Finished initrd-parse-etc.service - Reload Configuration from the Real Root.
OK: Reached target initrd-fs.target - Initrd File Systems.
OK: Reached target initrd.target - Initrd Default Target.
__: Starting dracut-pre-pivot.service - dracut pre-pivot and cleanup hook...
OK: Finished dracut-pre-pivot.service - dracut pre-pivot and cleanup hook.
__: Starting initrd-cleanup.service - Cleaning Up and Shutting Down Daemons...
OK: Stopped target network.target - Network.
OK: Stopped target timers.target - Timer Units.
OK: Closed dbus.socket - D-Bus System Message Bus Socket.
OK: Stopped dracut-pre-pivot.service - dracut pre-pivot and cleanup hook.
OK: Stopped target initrd.target - Initrd Default Target.
OK: Stopped target basic.target - Basic System.
OK: Stopped target initrd-root-device.target - Initrd Root Device.
OK: Stopped target initrd-usr-fs.target - Initrd /usr File System.
OK: Stopped target paths.target - Path Units.
OK: Stopped target remote-fs.target - Remote File Systems.
OK: Stopped target remote-fs-pre.target - Preparation for Remote File Systems.
OK: Stopped target slices.target - Slice Units.
OK: Stopped target sockets.target - Socket Units.
OK: Stopped target sysinit.target - System Initialization.
OK: Stopped target local-fs.target - Local File Systems.
OK: Stopped target swap.target - Swaps.
OK: Stopped dracut-initqueue.service - dracut initqueue hook.
__: Starting plymouth-switch-root.service - Plymouth switch root service...
OK: Stopped systemd-sysctl.service - Apply Kernel Variables.
OK: Stopped systemd-modules-load.service - Load Kernel Modules.
OK: Stopped systemd-tmpfiles-setup.service - Create Volatile Files and Directories.
OK: Stopped systemd-udev-trigger.service - Coldplug All udev Devices.
__: Stopping systemd-udevd.service - Rule-based Manager for Device Events and Files...
OK: Finished initrd-cleanup.service - Cleaning Up and Shutting Down Daemons.
OK: Stopped systemd-udevd.service - Rule-based Manager for Device Events and Files.
OK: Closed systemd-udevd-control.socket - udev Control Socket.
OK: Closed systemd-udevd-kernel.socket - udev Kernel Socket.
OK: Stopped dracut-pre-udev.service - dracut pre-udev hook.
OK: Stopped dracut-cmdline.service - dracut cmdline hook.
OK: Stopped dracut-cmdline-ask.service - dracut ask for additional cmdline parameters.
__: Starting initrd-udevadm-cleanup-db.service - Cleanup udev Database...
OK: Stopped systemd-tmpfiles-setup-dev.service - Create Static Device Nodes in /dev.
OK: Stopped kmod-static-nodes.service - Create List of Static Device Nodes.
OK: Stopped systemd-sysusers.service - Create System Users.
OK: Finished initrd-udevadm-cleanup-db.service - Cleanup udev Database.
OK: Reached target initrd-switch-root.target - Switch Root.
OK: Finished plymouth-switch-root.service - Plymouth switch root service.
__: Starting initrd-switch-root.service - Switch Root...
sleep 200
clear
nosleep
  : 
  : Welcome to Floppa OS!
  : 
sleep
sleep 200
OK: Stopped initrd-switch-root.service - Switch Root.
OK: Created slice system-getty.slice - Slice /system/getty.
OK: Created slice system-systemd\x2dfsck.slice - Slice /system/systemd-fsck.
OK: Created slice system-systemd\x2dzram\x2dsetup.slice - Slice /system/systemd-zram-setup.
OK: Created slice user.slice - User and Session Slice.
OK: Started systemd-ask-password-wall.path - Forward Password Requests to Wall Directory Watch.
OK: Set up automount proc-sys-fs-binfmt_misc.automount - Arbitrary Executable File Formats File System Automount Point.
OK: Reached target cryptsetup.target - Local Encrypted Volumes.
OK: Reached target getty.target - Login Prompts.
OK: Stopped target initrd-switch-root.target - Switch Root.
OK: Stopped target initrd-fs.target - Initrd File Systems.
OK: Stopped target initrd-root-fs.target - Initrd Root File System.
OK: Reached target integritysetup.target - Local Integrity Protected Volumes.
OK: Reached target slices.target - Slice Units.
OK: Reached target veritysetup.target - Local Verity Protected Volumes.
OK: Listening on dm-event.socket - Device-mapper event daemon FIFOs.
OK: Listening on lvm2-lvmpolld.socket - LVM2 poll daemon socket.
OK: Listening on systemd-coredump.socket - Process Core Dump Socket.
OK: Listening on systemd-initctl.socket - initctl Compatibility Named Pipe.
OK: Listening on systemd-oomd.socket - Userspace Out-Of-Memory (OOM) Killer Socket.
OK: Listening on systemd-udevd-control.socket - udev Control Socket.
OK: Listening on systemd-udevd-kernel.socket - udev Kernel Socket.
OK: Listening on systemd-userdbd.socket - User Database Manager Socket.
__: Mounting dev-hugepages.mount - Huge Pages File System...
__: Mounting dev-mqueue.mount - POSIX Message Queue File System...
__: Mounting sys-kernel-debug.mount - Kernel Debug File System...
__: Mounting sys-kernel-tracing.mount - Kernel Trace File System...
__: Starting kmod-static-nodes.service - Create List of Static Device Nodes...
__: Starting lvm2-monitor.service - Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
__: Starting modprobe@configfs.service - Load Kernel Module configfs...
__: Starting modprobe@dm_mod.service - Load Kernel Module dm_mod...
__: Starting modprobe@drm.service - Load Kernel Module drm...
__: Starting modprobe@fuse.service - Load Kernel Module fuse...
__: Starting modprobe@loop.service - Load Kernel Module loop...
OK: Stopped plymouth-switch-root.service - Plymouth switch root service.
OK: Stopped systemd-fsck-root.service - File System Check on Root Device.
OK: Stopped systemd-journald.service - Journal Service.
__: Starting systemd-journald.service - Journal Service...
__: Starting systemd-modules-load.service - Load Kernel Modules...
__: Starting systemd-network-generator.service - Generate network units from Kernel command line...
__: Starting systemd-remount-fs.service - Remount Root and Kernel File Systems...
__: Starting systemd-udev-trigger.service - Coldplug All udev Devices...
OK: Started systemd-journald.service - Journal Service.
OK: Mounted dev-hugepages.mount - Huge Pages File System.
OK: Mounted dev-mqueue.mount - POSIX Message Queue File System.
OK: Mounted sys-kernel-debug.mount - Kernel Debug File System.
OK: Mounted sys-kernel-tracing.mount - Kernel Trace File System.
OK: Finished kmod-static-nodes.service - Create List of Static Device Nodes.
OK: Finished modprobe@configfs.service - Load Kernel Module configfs.
OK: Finished modprobe@dm_mod.service - Load Kernel Module dm_mod.
OK: Finished modprobe@drm.service - Load Kernel Module drm.
OK: Finished modprobe@fuse.service - Load Kernel Module fuse.
OK: Finished modprobe@loop.service - Load Kernel Module loop.
OK: Finished systemd-modules-load.service - Load Kernel Modules.
OK: Finished systemd-network-generator.service - Generate network units from Kernel command line.
OK: Finished systemd-remount-fs.service - Remount Root and Kernel File Systems.
__: Mounting sys-fs-fuse-connections.mount - FUSE Control File System...
__: Starting systemd-journal-flush.service - Flush Journal to Persistent Storage...
__: Starting systemd-random-seed.service - Load/Save Random Seed...
__: Starting systemd-sysctl.service - Apply Kernel Variables...
__: Starting systemd-tmpfiles-setup-dev.service - Create Static Device Nodes in /dev...
OK: Mounted sys-fs-fuse-connections.mount - FUSE Control File System.
OK: Finished systemd-random-seed.service - Load/Save Random Seed.
OK: Finished systemd-sysctl.service - Apply Kernel Variables.
OK: Finished systemd-udev-trigger.service - Coldplug All udev Devices.
OK: Finished systemd-tmpfiles-setup-dev.service - Create Static Device Nodes in /dev.
__: Starting systemd-udevd.service - Rule-based Manager for Device Events and Files...
OK: Finished systemd-journal-flush.service - Flush Journal to Persistent Storage.
OK: Started systemd-udevd.service - Rule-based Manager for Device Events and Files.
__: Starting modprobe@configfs.service - Load Kernel Module configfs...
OK: Found device dev-zram0.device - /dev/zram0.
OK: Finished modprobe@configfs.service - Load Kernel Module configfs.
__: Starting modprobe@fuse.service - Load Kernel Module fuse...
__: Starting systemd-zram-setup@zram0.service - Create swap on /dev/zram0...
OK: Finished modprobe@fuse.service - Load Kernel Module fuse.
OK: Finished systemd-zram-setup@zram0.service - Create swap on /dev/zram0.
__: Activating swap dev-zram0.swap - Compressed Swap on /dev/zram0...
OK: Activated swap dev-zram0.swap - Compressed Swap on /dev/zram0.
OK: Reached target swap.target - Swaps.
__: Mounting tmp.mount - Temporary Directory /tmp...
OK: Mounted tmp.mount - Temporary Directory /tmp.
OK: Created slice system-systemd\x2dbacklight.slice - Slice /system/systemd-backlight.
__: Starting systemd-backlight@backlight:intel_backlight.service - Load/Save Screen Backlight Brightness of backlight:intel_backlight...
OK: Found device dev-disk-by\x2duuid-b80d5d3f\x2d371a\x2d4008\x2db19e\x2d3d0c5a8b05dc.device - WD_BLACK SN770 1TB fedora_liwireless.
OK: Finished systemd-backlight@backlight:intel_backlight.service - Load/Save Screen Backlight Brightness of backlight:intel_backlight.
OK: Finished lvm2-monitor.service - Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
OK: Reached target local-fs-pre.target - Preparation for Local File Systems.
__: Mounting home.mount - /home...
__: Mounting var-lib-snapd-snap-bare-5.mount - Mount unit for bare, revision 5...
__: Mounting var-lib-snapd-snap-chromium-2686.mount - Mount unit for chromium, revision 2686...
__: Mounting var-lib-snapd-snap-chromium-2695.mount - Mount unit for chromium, revision 2695...
__: Mounting var-lib-snapd-snap-compress\x2dvideo-29.mount - Mount unit for compress-video, revision 29...
__: Mounting var-lib-snapd-snap-compress\x2dvideo-30.mount - Mount unit for compress-video, revision 30...
__: Mounting var-lib-snapd-snap-core-16091.mount - Mount unit for core, revision 16091...
__: Mounting var-lib-snapd-snap-core-16202.mount - Mount unit for core, revision 16202...
__: Mounting var-lib-snapd-snap-core18-2790.mount - Mount unit for core18, revision 2790...
__: Mounting var-lib-snapd-snap-core18-2796.mount - Mount unit for core18, revision 2796...
__: Mounting var-lib-snapd-snap-core20-1974.mount - Mount unit for core20, revision 1974...
__: Mounting var-lib-snapd-snap-core20-2015.mount - Mount unit for core20, revision 2015...
__: Mounting var-lib-snapd-snap-core22-858.mount - Mount unit for core22, revision 858...
__: Mounting var-lib-snapd-snap-core22-864.mount - Mount unit for core22, revision 864...
__: Mounting var-lib-snapd-snap-cups-974.mount - Mount unit for cups, revision 974...
__: Mounting var-lib-snapd-snap-cups-980.mount - Mount unit for cups, revision 980...
__: Mounting var-lib-snapd-snap-gnome\x2d3\x2d28\x2d1804-194.mount - Mount unit for gnome-3-28-1804, revision 194...
__: Mounting var-lib-snapd-snap-gnome\x2d3\x2d28\x2d1804-198.mount - Mount unit for gnome-3-28-1804, revision 198...
__: Mounting var-lib-snapd-snap-gnome\x2d3\x2d38\x2d2004-140.mount - Mount unit for gnome-3-38-2004, revision 140...
__: Mounting var-lib-snapd-snap-gnome\x2d3\x2d38\x2d2004-143.mount - Mount unit for gnome-3-38-2004, revision 143...
__: Mounting var-lib-snapd-snap-gnome\x2d42\x2d2204-132.mount - Mount unit for gnome-42-2204, revision 132...
__: Mounting var-lib-snapd-snap-gnome\x2d42\x2d2204-141.mount - Mount unit for gnome-42-2204, revision 141...
__: Mounting var-lib-snapd-snap-gtk\x2dcommon\x2dthemes-1535.mount - Mount unit for gtk-common-themes, revision 1535...
__: Mounting var-lib-snapd-snap-htop-3758.mount - Mount unit for htop, revision 3758...
__: Mounting var-lib-snapd-snap-htop-3873.mount - Mount unit for htop, revision 3873...
__: Mounting var-lib-snapd-snap-intellij\x2didea\x2dcommunity-464.mount - Mount unit for intellij-idea-community, revision 464...
__: Mounting var-lib-snapd-snap-intellij\x2didea\x2dcommunity-467.mount - Mount unit for intellij-idea-community, revision 467...
__: Mounting var-lib-snapd-snap-kde\x2dframeworks\x2d5\x2dcore18-32.mount - Mount unit for kde-frameworks-5-core18, revision 32...
__: Mounting var-lib-snapd-snap-kde\x2dframeworks\x2d5\x2dcore18-35.mount - Mount unit for kde-frameworks-5-core18, revision 35...
__: Mounting var-lib-snapd-snap-ksnip-443.mount - Mount unit for ksnip, revision 443...
__: Mounting var-lib-snapd-snap-ksnip-488.mount - Mount unit for ksnip, revision 488...
__: Mounting var-lib-snapd-snap-riseup\x2dvpn-179.mount - Mount unit for riseup-vpn, revision 179...
__: Mounting var-lib-snapd-snap-snapd-20092.mount - Mount unit for snapd, revision 20092...
__: Mounting var-lib-snapd-snap-snapd-20290.mount - Mount unit for snapd, revision 20290...
__: Mounting var-lib-snapd-snap-webots-24.mount - Mount unit for webots, revision 24...
__: Mounting var-lib-snapd-snap-webots-25.mount - Mount unit for webots, revision 25...
__: Mounting var-lib-snapd-snap-zoom\x2dclient-210.mount - Mount unit for zoom-client, revision 210...
__: Mounting var-lib-snapd-snap-zoom\x2dclient-218.mount - Mount unit for zoom-client, revision 218...
__: Starting systemd-fsck@dev-disk-by\x2duuid-887a5188\x2df6a0\x2d4588\x2d9287\x2d9b72a7cd1710.service - File System Check on /dev/disk/by-uuid/887a5188-f6a0-4588-9287-9b72a7cd1710...
__: Starting systemd-fsck@dev-disk-by\x2duuid-B865\x2d4EC4.service - File System Check on /dev/disk/by-uuid/B865-4EC4...
OK: Mounted home.mount - /home.
OK: Mounted var-lib-snapd-snap-bare-5.mount - Mount unit for bare, revision 5.
OK: Mounted var-lib-snapd-snap-chromium-2686.mount - Mount unit for chromium, revision 2686.
OK: Mounted var-lib-snapd-snap-chromium-2695.mount - Mount unit for chromium, revision 2695.
OK: Mounted var-lib-snapd-snap-compress\x2dvideo-29.mount - Mount unit for compress-video, revision 29.
OK: Mounted var-lib-snapd-snap-compress\x2dvideo-30.mount - Mount unit for compress-video, revision 30.
OK: Mounted var-lib-snapd-snap-core-16091.mount - Mount unit for core, revision 16091.
OK: Mounted var-lib-snapd-snap-core-16202.mount - Mount unit for core, revision 16202.
OK: Mounted var-lib-snapd-snap-core18-2790.mount - Mount unit for core18, revision 2790.
OK: Mounted var-lib-snapd-snap-core18-2796.mount - Mount unit for core18, revision 2796.
OK: Mounted var-lib-snapd-snap-core20-1974.mount - Mount unit for core20, revision 1974.
OK: Mounted var-lib-snapd-snap-core20-2015.mount - Mount unit for core20, revision 2015.
OK: Mounted var-lib-snapd-snap-core22-858.mount - Mount unit for core22, revision 858.
OK: Mounted var-lib-snapd-snap-core22-864.mount - Mount unit for core22, revision 864.
OK: Mounted var-lib-snapd-snap-cups-974.mount - Mount unit for cups, revision 974.
OK: Mounted var-lib-snapd-snap-cups-980.mount - Mount unit for cups, revision 980.
OK: Mounted var-lib-snapd-snap-gnome\x2d3\x2d28\x2d1804-194.mount - Mount unit for gnome-3-28-1804, revision 194.
OK: Mounted var-lib-snapd-snap-gnome\x2d3\x2d28\x2d1804-198.mount - Mount unit for gnome-3-28-1804, revision 198.
OK: Mounted var-lib-snapd-snap-gnome\x2d3\x2d38\x2d2004-140.mount - Mount unit for gnome-3-38-2004, revision 140.
OK: Mounted var-lib-snapd-snap-gnome\x2d3\x2d38\x2d2004-143.mount - Mount unit for gnome-3-38-2004, revision 143.
OK: Mounted var-lib-snapd-snap-gnome\x2d42\x2d2204-132.mount - Mount unit for gnome-42-2204, revision 132.
OK: Mounted var-lib-snapd-snap-gnome\x2d42\x2d2204-141.mount - Mount unit for gnome-42-2204, revision 141.
OK: Mounted var-lib-snapd-snap-gtk\x2dcommon\x2dthemes-1535.mount - Mount unit for gtk-common-themes, revision 1535.
OK: Mounted var-lib-snapd-snap-htop-3758.mount - Mount unit for htop, revision 3758.
OK: Mounted var-lib-snapd-snap-htop-3873.mount - Mount unit for htop, revision 3873.
OK: Mounted var-lib-snapd-snap-intellij\x2didea\x2dcommunity-464.mount - Mount unit for intellij-idea-community, revision 464.
OK: Mounted var-lib-snapd-snap-intellij\x2didea\x2dcommunity-467.mount - Mount unit for intellij-idea-community, revision 467.
OK: Mounted var-lib-snapd-snap-kde\x2dframeworks\x2d5\x2dcore18-32.mount - Mount unit for kde-frameworks-5-core18, revision 32.
OK: Mounted var-lib-snapd-snap-kde\x2dframeworks\x2d5\x2dcore18-35.mount - Mount unit for kde-frameworks-5-core18, revision 35.
OK: Mounted var-lib-snapd-snap-ksnip-443.mount - Mount unit for ksnip, revision 443.
OK: Mounted var-lib-snapd-snap-ksnip-488.mount - Mount unit for ksnip, revision 488.
OK: Mounted var-lib-snapd-snap-riseup\x2dvpn-179.mount - Mount unit for riseup-vpn, revision 179.
OK: Mounted var-lib-snapd-snap-snapd-20092.mount - Mount unit for snapd, revision 20092.
OK: Mounted var-lib-snapd-snap-snapd-20290.mount - Mount unit for snapd, revision 20290.
OK: Mounted var-lib-snapd-snap-webots-24.mount - Mount unit for webots, revision 24.
OK: Mounted var-lib-snapd-snap-webots-25.mount - Mount unit for webots, revision 25.
OK: Mounted var-lib-snapd-snap-zoom\x2dclient-210.mount - Mount unit for zoom-client, revision 210.
OK: Mounted var-lib-snapd-snap-zoom\x2dclient-218.mount - Mount unit for zoom-client, revision 218.
OK: Finished systemd-fsck@dev-disk-by\x2duuid-887a5188\x2df6a0\x2d4588\x2d9287\x2d9b72a7cd1710.service - File System Check on /dev/disk/by-uuid/887a5188-f6a0-4588-9287-9b72a7cd1710.
OK: Finished systemd-fsck@dev-disk-by\x2duuid-B865\x2d4EC4.service - File System Check on /dev/disk/by-uuid/B865-4EC4.
__: Mounting boot.mount - /boot...
__: Starting modprobe@dm_mod.service - Load Kernel Module dm_mod...
__: Starting modprobe@loop.service - Load Kernel Module loop...
OK: Mounted boot.mount - /boot.
OK: Finished modprobe@dm_mod.service - Load Kernel Module dm_mod.
OK: Finished modprobe@loop.service - Load Kernel Module loop.
__: Mounting boot-efi.mount - /boot/efi...
OK: Mounted boot-efi.mount - /boot/efi.
OK: Reached target local-fs.target - Local File Systems.
__: Starting import-state.service - Import network configuration from initramfs...
__: Starting plymouth-read-write.service - Tell Plymouth To Write Out Runtime Data...
__: Starting systemd-binfmt.service - Set Up Additional Binary Formats...
__: Starting systemd-boot-update.service - Automatic Boot Loader Update...
__: Mounting proc-sys-fs-binfmt_misc.mount - Arbitrary Executable File Formats File System...
OK: Finished systemd-boot-update.service - Automatic Boot Loader Update.
OK: Finished plymouth-read-write.service - Tell Plymouth To Write Out Runtime Data.
OK: Mounted proc-sys-fs-binfmt_misc.mount - Arbitrary Executable File Formats File System.
OK: Finished import-state.service - Import network configuration from initramfs.
OK: Finished systemd-binfmt.service - Set Up Additional Binary Formats.
__: Starting systemd-tmpfiles-setup.service - Create Volatile Files and Directories...
OK: Finished systemd-tmpfiles-setup.service - Create Volatile Files and Directories.
__: Mounting var-lib-nfs-rpc_pipefs.mount - RPC Pipe File System...
__: Starting auditd.service - Security Auditing Service...
__: Starting systemd-oomd.service - Userspace Out-Of-Memory (OOM) Killer...
__: Starting systemd-resolved.service - Network Name Resolution...
__: Starting systemd-userdbd.service - User Database Manager...
OK: Started auditd.service - Security Auditing Service.
__: Starting systemd-update-utmp.service - Record System Boot/Shutdown in UTMP...
OK: Started systemd-userdbd.service - User Database Manager.
OK: Mounted var-lib-nfs-rpc_pipefs.mount - RPC Pipe File System.
OK: Reached target rpc_pipefs.target.
OK: Finished systemd-update-utmp.service - Record System Boot/Shutdown in UTMP.
OK: Started systemd-oomd.service - Userspace Out-Of-Memory (OOM) Killer.
OK: Started systemd-resolved.service - Network Name Resolution.
OK: Reached target nss-lookup.target - Host and Network Name Lookups.
OK: Reached target sysinit.target - System Initialization.
OK: Started cups.path - CUPS Scheduler.
OK: Started dnf-makecache.timer - dnf makecache --timer.
OK: Started fstrim.timer - Discard unused blocks once a week.
OK: Started logrotate.timer - Daily rotation of log files.
OK: Started plocate-updatedb.timer - Update the plocate database daily.
OK: Started raid-check.timer - Weekly RAID setup health check.
OK: Started systemd-tmpfiles-clean.timer - Daily Cleanup of Temporary Directories.
OK: Started unbound-anchor.timer - daily update of the root trust anchor for DNSSEC.
OK: Reached target paths.target - Path Units.
OK: Reached target timers.target - Timer Units.
OK: Listening on avahi-daemon.socket - Avahi mDNS/DNS-SD Stack Activation Socket.
OK: Listening on cups.socket - CUPS Scheduler.
OK: Listening on dbus.socket - D-Bus System Message Bus Socket.
__: Starting docker.socket - Docker Socket for the API...
OK: Listening on iscsid.socket - Open-iSCSI iscsid Socket.
OK: Listening on iscsiuio.socket - Open-iSCSI iscsiuio Socket.
OK: Listening on pcscd.socket - PC/SC Smart Card Daemon Activation Socket.
__: Starting snapd.socket - Socket activation for snappy daemon...
OK: Listening on sssd-kcm.socket - SSSD Kerberos Cache Manager responder socket.
OK: Listening on docker.socket - Docker Socket for the API.
OK: Listening on snapd.socket - Socket activation for snappy daemon.
OK: Reached target sockets.target - Socket Units.
__: Starting dbus-broker.service - D-Bus System Message Bus...
OK: Started dbus-broker.service - D-Bus System Message Bus.
OK: Reached target basic.target - Basic System.
OK: Started alsa-state.service - Manage Sound Card State (restore and store).
OK: Reached target sound.target - Sound Card.
__: Starting avahi-daemon.service - Avahi mDNS/DNS-SD Stack...
__: Starting dracut-shutdown.service - Restore /run/initramfs on shutdown...
OK: Started irqbalance.service - irqbalance daemon.
__: Starting livesys.service - LSB: Init script for live image....
__: Starting lm_sensors.service - Hardware Monitoring Sensors...
OK: Started mcelog.service - Machine Check Exception Logging Daemon.
__: Starting polkit.service - Authorization Manager...
__: Starting powertop.service - PowerTOP autotuner...
__: Starting rsyslog.service - System Logging Service...
__: Starting rtkit-daemon.service - RealtimeKit Scheduling Policy Service...
__: Starting smartd.service - Self Monitoring and Reporting Technology (SMART) Daemon...
OK: Reached target nss-user-lookup.target - User and Group Name Lookups.
__: Starting accounts-daemon.service - Accounts Service...
__: Starting systemd-logind.service - User Login Management...
__: Starting udisks2.service - Disk Manager...
__: Starting upower.service - Daemon for power management...
OK: Started rsyslog.service - System Logging Service.
OK: Finished dracut-shutdown.service - Restore /run/initramfs on shutdown.
OK: Started livesys.service - LSB: Init script for live image..
OK: Started smartd.service - Self Monitoring and Reporting Technology (SMART) Daemon.
OK: Started rtkit-daemon.service - RealtimeKit Scheduling Policy Service.
OK: Started avahi-daemon.service - Avahi mDNS/DNS-SD Stack.
__: Starting abrtd.service - ABRT Daemon...
__: Starting chronyd.service - NTP client/server...
__: Starting livesys-late.service - SYSV: Late init script for live image....
OK: Finished lm_sensors.service - Hardware Monitoring Sensors.
OK: Started livesys-late.service - SYSV: Late init script for live image..
OK: Started polkit.service - Authorization Manager.
__: Starting ModemManager.service - Modem Manager...
__: Starting firewalld.service - firewalld - dynamic firewall daemon...
__: Starting modprobe@drm.service - Load Kernel Module drm...
OK: Finished modprobe@drm.service - Load Kernel Module drm.
OK: Started systemd-logind.service - User Login Management.
OK: Started chronyd.service - NTP client/server.
OK: Started accounts-daemon.service - Accounts Service.
__: Starting bolt.service - Thunderbolt system service...
OK: Started upower.service - Daemon for power management.
OK: Started ModemManager.service - Modem Manager.
OK: Started udisks2.service - Disk Manager.
OK: Started bolt.service - Thunderbolt system service.
__: Starting bluetooth.service - Bluetooth service...
OK: Started bluetooth.service - Bluetooth service.
OK: Reached target bluetooth.target - Bluetooth Support.
__: Starting systemd-hostnamed.service - Hostname Service...
OK: Started systemd-hostnamed.service - Hostname Service.
OK: Started firewalld.service - firewalld - dynamic firewall daemon.
OK: Reached target network-pre.target - Preparation for Network.
__: Starting NetworkManager.service - Network Manager...
OK: Started NetworkManager.service - Network Manager.
OK: Reached target network.target - Network.
__: Starting NetworkManager-wait-online.service - Network Manager Wait Online...
__: Starting containerd.service - containerd container runtime...
__: Starting cups.service - CUPS Scheduler...
__: Starting gssproxy.service - GSSAPI Proxy Daemon...
OK: Started snap.cups.cups-browsed.service - Service for snap application cups.cups-browsed.
OK: Started snap.cups.cupsd.service - Service for snap application cups.cupsd.
__: Starting NetworkManager-dispatcher.service - Network Manager Script Dispatcher Service...
OK: Started abrtd.service - ABRT Daemon.
OK: Started abrt-journal-core.service - ABRT coredumpctl message creator.
OK: Started abrt-oops.service - ABRT kernel log watcher.
OK: Started abrt-xorg.service - ABRT Xorg log watcher.
OK: Started NetworkManager-dispatcher.service - Network Manager Script Dispatcher Service.
__: Starting colord.service - Manage, Install and Generate Color Profiles...
OK: Started gssproxy.service - GSSAPI Proxy Daemon.
OK: Reached target nfs-client.target - NFS client services.
OK: Started colord.service - Manage, Install and Generate Color Profiles.
OK: Started cups.service - CUPS Scheduler.
OK: Started containerd.service - containerd container runtime.
__: Starting wpa_supplicant.service - WPA supplicant...
OK: Started wpa_supplicant.service - WPA supplicant.
OK: Finished powertop.service - PowerTOP autotuner.
OK: Finished NetworkManager-wait-online.service - Network Manager Wait Online.
OK: Reached target network-online.target - Network is Online.
__: Starting docker.service - Docker Application Container Engine...
OK: Reached target remote-fs-pre.target - Preparation for Remote File Systems.
OK: Reached target remote-fs.target - Remote File Systems.
__: Starting rpc-statd-notify.service - Notify NFS peers of a restart...
__: Starting systemd-user-sessions.service - Permit User Sessions...
OK: Started rpc-statd-notify.service - Notify NFS peers of a restart.
OK: Finished systemd-user-sessions.service - Permit User Sessions.
OK: Started atd.service - Deferred execution scheduler.
OK: Started crond.service - Command Scheduler.
__: Starting plymouth-quit-wait.service - Hold until boot process finishes up...
__: Starting plymouth-quit.service - Terminate Plymouth Boot Screen...
sleep 800
`
	.split("\n");
