// this file was generated by `gen_filesystem.py`

import { filesystem } from "./filesys";

filesystem._init_add_file("/bin/help.js", `console.log(lib);
args = lib.args(process.argv, ["--help", "-h"]);
const help = args["--help"] || args["-h"];

if (help) {
	console.println("yeehaw");
	return;
}
`);
filesystem._init_add_file("/bin/cd.js", ``);
filesystem._init_add_file("/bin/ls.js", ``);

filesystem._init_add_file("/lib/args.js", `function process_name(argv0) {
	return /\\/([^/]+)\$/.exec(argv0)[1];
}

function args(argv, expected_args) {
	let args = {};

	let prev_arg = null;
	argv.slice(1).forEach((arg) => {
		if (arg.startsWith("-")) {
			args[arg] = true;
			prev_arg = arg;
		} else if (prev_arg) {
			args[prev_arg] = arg;
			prev_arg = null;
		} else prev_arg = null;
	});

	for (const arg of Object.keys(args)) {
		if (!expected_args.includes(arg)) {
			throw \`\${process_name(argv[0])}: \${arg}: Unknown option\`;
		}
	}

	return args;
}

return args;
`);
filesystem._init_add_file("/lib/man.js", ``);

export { filesystem }