// This file is automatically generated by `gen_post_its.py`

import img0 from "./generated/0.png";
import img1 from "./generated/1.png";
import img2 from "./generated/2.png";
import img3 from "./generated/3.png";
import img4 from "./generated/4.png";
import img5 from "./generated/5.png";
import img6 from "./generated/6.png";
import img7 from "./generated/7.png";
import img8 from "./generated/8.png";
import img9 from "./generated/9.png";
import img10 from "./generated/10.png";
import img11 from "./generated/11.png";
import img12 from "./generated/12.png";
import img13 from "./generated/13.png";
import img14 from "./generated/14.png";
import img15 from "./generated/15.png";

export const post_its = [img0,img1,img2,img3,img4,img5,img6,img7,img8,img9,img10,img11,img12,img13,img14,img15];