# Templates used as, well, templates, for windows
templates:
  - id: dialog
    file: Dialog
    mode: props content(markdown)

  - id: window
    file: Window
    mode: component

# the actual list of windows
registry:
  - id: welcome
    base: dialog
    title: Welcome!
    content: |
      # Welcome to Floppa OS!

      This is my website. Welcome!

      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
      occaecat.
    width: [120, 90]

  - id: settings
    base: window
    title: System Settings
    file: Settings
    app:
      icon: settings
      row: -1

  - id: terminal
    base: window
    title: Terminal
    file: Terminal
    app:
      icon: terminal
      row: -1
