// This file is automatially generated by `gen/gen_registry.py`
export type Item = { component: any; props: { [key: string]: any } };
export let registry: { [key: string]: Item } = {};

import dialog from "./Dialog.svelte";
import window from "./Window.svelte";

registry["welcome"] = { component: dialog, props: {"width": [120, 90], "height": [90, 100]} };
